# Generated by Django 4.2 on 2024-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personnel_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='médecin/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(choices=[('Médecin Generaliste', 'Médecin Généraliste'), ('Médecin Cardiologue', 'Médecin Cardiologue'), ('Médecin Dermatologue', 'Médecin Dermatologue'), ('Médecin Pediatre', 'Médecin Pédiatre'), ('Médecin Chirurgien', 'Médecin Chirurgien'), ('Médecin Radiologue', 'Médecin Radiologue'), ('Médecin Psychiatre', 'Médecin Psychiatre'), ('Médecin Gynecologue', 'Médecin Gynécologue'), ('Infirmier', 'Infirmier'), ('Secretaire', 'Secrétaire'), ('Technicien', 'Technicien')], max_length=100),
        ),
    ]
