# Generated by Django 4.2 on 2024-11-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_photo_alter_personnel_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, default='médecin/doctor.png', null=True, upload_to='médecin/'),
        ),
    ]
