# Generated by Django 4.2 on 2024-12-08 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_personnel_date_left_alter_personnel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(choices=[('Médecin Généraliste', 'Médecin Généraliste'), ('Médecin Cardiologue', 'Médecin Cardiologue'), ('Médecin Dermatologue', 'Médecin Dermatologue'), ('Médecin Pédiatre', 'Médecin Pédiatre'), ('Médecin Chirurgien', 'Médecin Chirurgien'), ('Médecin Radiologue', 'Médecin Radiologue'), ('Médecin Psychiatre', 'Médecin Psychiatre'), ('Médecin Gynécologue', 'Médecin Gynécologue'), ('Infirmier', 'Infirmier'), ('Secrétaire', 'Secrétaire'), ('Technicien', 'Technicien')], max_length=100),
        ),
    ]
