# Generated by Django 4.2 on 2024-12-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
