# Generated by Django 4.2 on 2024-12-03 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_customuser_age_customuser_gender_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 14, 48, 3, 354192, tzinfo=datetime.timezone.utc)),
        ),
    ]
