# Generated by Django 4.2 on 2024-12-03 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_customuser_date_left_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emergency_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 19, 3, 49, 167, tzinfo=datetime.timezone.utc)),
        ),
    ]
