# Generated by Django 4.2 on 2024-12-08 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_customuser_emergency_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
