# Generated by Django 4.2 on 2024-12-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_customuser_face_encoding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
