# Generated by Django 4.2 on 2024-12-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_customuser_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='face_image',
        ),
    ]
