# Generated by Django 4.2 on 2024-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_remove_customuser_face_encoding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
