# Generated by Django 4.2 on 2024-12-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_customuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
    ]
