# Generated by Django 4.2 on 2024-12-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_remove_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
